version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: ./script/bootstrap -u
  test:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: ./script/test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
